interface GetCommonMetadataArgs {
  title: string;
  description?: string;
  images?: {
    url: string;
    alt: string;
  }[];
  keywords?: string[];
}
export const GetCommonMetadata = ({
  title,
  description,
  images,
  keywords,
}: GetCommonMetadataArgs) => {
  return {
    title: title ?? "Create Next App",
    description: description ?? "Generated by create next app",
    images,
    keywords,
  };
};
