interface GetCommonMetadataArgs {
  title: string;
  description?: string;
  images?: {
    url: string;
    alt: string;
  }[];
  keywords?: string[];
}

export const GetCommonMetadata = ({
  title,
  description,
  images,
  keywords,
}: GetCommonMetadataArgs) => {
  return {
    title: title ?? "Create Next App",
    description: description ?? "Generated by create next app",
    icons: [{ rel: "icon", url: "/e-co logo.png" }],
    images: images ?? [
      {
        url: "/default-og.png",
        alt: "Default Open Graph Image",
      },
    ],
    keywords: keywords?.map((k) => k.toLowerCase()),
  };
};
